package adcert

var private = `-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIHzgoLkETbOdLrMM0VZMdqKyoPtlhJJqS8EmC5VIUi5FoAoGCCqGSM49
AwEHoUQDQgAEbf1bhEQenrJYxTJsg0hBuEh89+BR3L+xzxKsG1T2m6TR9bhO9rDc
2BX9ECYmdz1EihqFB9cMgpnA+aMHDa8TPA==
-----END EC PRIVATE KEY-----
`

var public = `-----BEGIN CERTIFICATE-----
MIICFzCCAbygAwIBAgIJAMhtuy97yJ44MAoGCCqGSM49BAMCMGYxCzAJBgNVBAYT
AlVTMQ0wCwYDVQQIDARVdGFoMRcwFQYDVQQHDA5TYWx0IExha2UgQ2l0eTEPMA0G
A1UECgwGU1NQIHYxMQwwCgYDVQQLDANTU1AxEDAOBgNVBAMMB3NzcC5jb20wHhcN
MTgwODE1MTYzMzQxWhcNMTkwODE1MTYzMzQxWjBmMQswCQYDVQQGEwJVUzENMAsG
A1UECAwEVXRhaDEXMBUGA1UEBwwOU2FsdCBMYWtlIENpdHkxDzANBgNVBAoMBlNT
UCB2MTEMMAoGA1UECwwDU1NQMRAwDgYDVQQDDAdzc3AuY29tMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEbf1bhEQenrJYxTJsg0hBuEh89+BR3L+xzxKsG1T2m6TR
9bhO9rDc2BX9ECYmdz1EihqFB9cMgpnA+aMHDa8TPKNTMFEwHQYDVR0OBBYEFBRV
RBu7knxTjfUfJOQ/d1mGk6MuMB8GA1UdIwQYMBaAFBRVRBu7knxTjfUfJOQ/d1mG
k6MuMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAM+j0XfUwtjP
luy7S7O7Dv1imq6pYEnPmtp9wpLOyawOAiEAi1Mk8JgouGiWgXyDu8OwSj3fScSy
pnjYSWXqiQnHG9s=
-----END CERTIFICATE-----
`
